### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by robbiet480** [Bearcatter/bearcatter#6]
Made a massive breakthrough tonight on the SDS100. There's a previously undocumented command to stream audio files over USB as they come in. It's a left over from the HomePatrol. This means with a single cable, we can grab audio as well as data. It's not as real time as using the line in, but I'd prefer grabbing clean cut and properly tagged audio anyway, so its worth a few second delay while the file transfers over. The only downside I've found thus far is if you navigate away from the scanner status screen, the transfer fails. This may be a problem with HPe-rc though, it just may not be expecting the command structure of known SDS100 commands. The WAV files are output with the normal Uniden headers too.

To get this added to sds200:
~~- Implement the HP command structure, which is tab based and requires a checksum on every message~~
~~- Implement the WAV header reader (could be good for other things anyway)~~

I'm pretty much just writing this as a note to myself for tomorrow. 

- [HPe-rc](https://hp.xoynq.com/#audio-feed) was invaluable (if you want to try it, comment out lines 1116-1118, otherwise it'll crash after opening serial port).
- [Spec is here](http://info.uniden.com/twiki/pub/HomePatrol/TechnicalDocs/HomePatrol-1_Remote_Control_Specification_V2.05.pdf)
- [Tip off here](https://forums.radioreference.com/threads/sds100-protocol-docs.373083/page-2#post-2961047)

**Comment by rabarar** [comment]
What’s the command? I’ll see if it exists on the SDS200 as well.

**Comment by robbiet480** [comment]
I haven't replicated the exact commands HPe-rc is sending yet, hoping to do that today to determine if this path is viable (bit worried that the audio feed and PSI won't play nice together).

**Comment by rabarar** [comment]
PSI, and RTSP work without any issue. If you use the URI rtsp://IP:554/au:scanner.au you can stream to VLC for example while the client streams PSI at 50ms - no isssues.

**Comment by robbiet480** [comment]
Good to know, but I'm worried about PSI and audio feed on the SDS100 since it all goes through the same serial link. If PSI comes in the middle of an audio feed, can we and the scanner handle that?

**Comment by rabarar** [comment]
yeah - not sure how that’s going to work…

The commands that you show aren’t going to be supported by the SDS200 I imagine - Unless it’s attached via USB and in Serial Mode - would be an interesting experiment to see how compatible SDS100/200 are in USB mode.

**Comment by robbiet480** [comment]
Good news/bad news for SDS200 owners:

Good news: Audio Feed does work, exactly as on SDS100
Bad news: It only appears to work via the miniUSB port. All attempts to use any Home Patrol commands via UDP have failed thus far. `cdb,M,0` and `cdb,M,1` both work (that command controls whether the CRC check is confirmed on each message) so some part of Home Patrol spec is available via UDP.

**Comment by robbiet480** [comment]
Once #13 is merged, I am calling 1.0 of audio complete. There’s still a few improvements to be made, like ensuring we correctly do the file transfer dance and properly configuring logging, but it’s fine for now.
