### ISSUE TITLE
Rename & move

### ISSUE THREAD

**Issue by robbiet480** [Bearcatter/bearcatter#8]
My project was named `sds-central`, because I am bad at coming up with names. Should we rename sds200 to something more generic since it supports SDS100 now?

In addition, I’m wondering if it might not be a bad idea to move this project to a Github org, purely because I expect at some point someone will want to build a nice web UI to work with the web server and we will want another repo for that. Might be good to get that move out of the way now instead of getting months into this and having to change URLs everywhere.

**Comment by rabarar** [comment]
that makes sense - here’s a few ideas

-  polyden - (as in poly vs uni)
- bearcatter (play on the product name)
- freebear (play on open source)
- scantopia (way out there and desperate for a name)
- other?


Github org makes sense  - let’s settle on a name and I’ll create an org…

**Comment by robbiet480** [comment]
How about bearcatter?

**Comment by rabarar** [comment]
bearcatter it is.

**Comment by robbiet480** [comment]
@rabarar Can you give me admin on this repo for a few? Just want to tweak some settings and move client code into its own repo.

**Comment by rabarar** [comment]
Def

**Comment by rabarar** [comment]
do me a favor and let me know what mods you made.

thx

**Comment by robbiet480** [comment]
Only things I've already done are updating the repo description and disabling merge commits (so we just have squash and rebase merges). Now just doing some light housekeeping: Updating README.md here for the rename and moving the client code into its own repo. Will let you know what else I get up to and once my admin privs can be removed.

**Comment by rabarar** [comment]
Sounds good - thx!

**Comment by robbiet480** [comment]
@rabarar Only other settings change I made was adding protection to master branch and requiring PR reviews. You can now remove my admin privileges. If you could also merge #9, that would be great. Thanks!

**Comment by rabarar** [comment]
Perfect. Will do.
